from __future__ import annotations

from typing import Dict, Tuple

from asset_allocation_runtime_common.market_data.gold_sync_contracts import get_sync_config
SUPPORTED_GOLD_LOOKUP_TABLES: Tuple[str, ...] = (
    "market_data",
    "finance_data",
    "earnings_data",
    "price_target_data",
    "government_signal_issuer_daily",
    "regime_inputs_daily",
    "regime_history",
    "regime_latest",
    "regime_transitions",
)

TABLE_SOURCE_JOBS: Dict[str, str] = {
    "market_data": "tasks.market_data.gold_market_data",
    "finance_data": "tasks.finance_data.gold_finance_data",
    "earnings_data": "tasks.earnings_data.gold_earnings_data",
    "price_target_data": "tasks.price_target_data.gold_price_target_data",
    "government_signal_issuer_daily": "tasks.government_signal_data.gold_government_signal_data",
    "regime_inputs_daily": "tasks.regime_data.gold_regime_data",
    "regime_history": "tasks.regime_data.gold_regime_data",
    "regime_latest": "tasks.regime_data.gold_regime_data",
    "regime_transitions": "tasks.regime_data.gold_regime_data",
}

GOVERNMENT_SIGNAL_ISSUER_DAILY_COLUMNS: Tuple[str, ...] = (
    "as_of_date",
    "symbol",
    "issuer_name",
    "congress_purchase_count_1d",
    "congress_purchase_count_7d",
    "congress_purchase_count_30d",
    "congress_purchase_count_90d",
    "congress_sale_count_1d",
    "congress_sale_count_7d",
    "congress_sale_count_30d",
    "congress_sale_count_90d",
    "congress_net_amount_proxy_usd_30d",
    "congress_net_amount_proxy_usd_90d",
    "congress_amendment_rate_90d",
    "congress_late_filing_rate_90d",
    "congress_unique_members_90d",
    "congress_unique_committees_90d",
    "contract_award_count_30d",
    "contract_award_count_90d",
    "contract_obligation_delta_usd_30d",
    "contract_obligation_delta_usd_90d",
    "contract_outlay_delta_usd_30d",
    "contract_outlay_delta_usd_90d",
    "contract_modification_count_90d",
    "contract_option_exercise_count_90d",
    "contract_termination_count_90d",
    "contract_cancellation_count_90d",
    "contract_protest_count_90d",
    "contract_unique_awarding_agencies_90d",
    "contract_unique_naics_90d",
    "contract_unique_psc_90d",
    "last_congress_trade_at",
    "last_contract_event_at",
    "mapping_status",
)

REGIME_TABLE_COLUMNS: Dict[str, Tuple[str, ...]] = {
    "regime_inputs_daily": (
        "as_of_date",
        "spy_close",
        "return_1d",
        "return_20d",
        "rvol_10d_ann",
        "vix_spot_close",
        "vix3m_close",
        "vix_slope",
        "trend_state",
        "curve_state",
        "vix_gt_32_streak",
        "inputs_complete_flag",
        "computed_at",
    ),
    "regime_history": (
        "as_of_date",
        "effective_from_date",
        "model_name",
        "model_version",
        "regime_code",
        "regime_status",
        "matched_rule_id",
        "halt_flag",
        "halt_reason",
        "spy_return_20d",
        "rvol_10d_ann",
        "vix_spot_close",
        "vix3m_close",
        "vix_slope",
        "trend_state",
        "curve_state",
        "vix_gt_32_streak",
        "computed_at",
    ),
    "regime_latest": (
        "model_name",
        "model_version",
        "as_of_date",
        "effective_from_date",
        "regime_code",
        "regime_status",
        "matched_rule_id",
        "halt_flag",
        "halt_reason",
        "spy_return_20d",
        "rvol_10d_ann",
        "vix_spot_close",
        "vix3m_close",
        "vix_slope",
        "trend_state",
        "curve_state",
        "vix_gt_32_streak",
        "computed_at",
    ),
    "regime_transitions": (
        "model_name",
        "model_version",
        "effective_from_date",
        "prior_regime_code",
        "new_regime_code",
        "trigger_rule_id",
        "computed_at",
    ),
}


def expected_gold_lookup_columns() -> Dict[str, Tuple[str, ...]]:
    return {
        "market_data": tuple(get_sync_config("market").columns),
        "finance_data": tuple(get_sync_config("finance").columns),
        "earnings_data": tuple(get_sync_config("earnings").columns),
        "price_target_data": tuple(get_sync_config("price-target").columns),
        "government_signal_issuer_daily": GOVERNMENT_SIGNAL_ISSUER_DAILY_COLUMNS,
        **REGIME_TABLE_COLUMNS,
    }
